### ISSUE TITLE
建议补充 CQ 码的相关文档

### ISSUE THREAD

**Issue by Shigma** [cqhttp/cqhttp-protocol#1]
我是说，由于 CoolQ 官方的文档站已经没了，希望 CQHTTP 可以作为协议制定方，向文档中补充完整的 CQ 码说明。

更新：之前没看到 TODO 抱歉了……

**Comment by richardchien** [comment]
嗯，是打算把 CQ 原生的也写进来的

**Comment by richardchien** [comment]
OK，已经补充好了
